### ISSUE TITLE
Heterogeneous (partially archived) setup

### ISSUE THREAD

**Issue by 0x7CFE** [djkoloski/rkyv#100]
Hi! Is it possible to create a setup where one can have once serialized tree that is loaded as a writeable resource? So that when write occurs, a serialized node is replaced by an in-memory representation? Something like a read-only filesystem with writable overlay that can later be serialized too to merge serialized and not-yet-serialized stuff into a single archive.

**Comment by djkoloski** [comment]
You might be able to do this by defining an enum (i.e `Heterogeneous<T>`) with an `Archived` variant containing an `Archived<T>` and an `Unarchived` variant containing a `T`. The serialization implementation would just check the variant and either deserialize and re-serialize (if `Archived`) or just serialize (if `Unarchived`). There are a few more things to figure out, but I think that general shape will work.

As always, make sure your types are archive-safe (enums should have a defined `repr`) and you should be good to go.

**Comment by djkoloski** [comment]
Closing this for now, feel free to reopen if you have more questions 🙂
