### ISSUE TITLE
Endian-agnostic archived types

### ISSUE THREAD

**Issue by djkoloski** [djkoloski/rkyv#104]
Due to portability concerns, it would be good to give feature options for endianness:

`endian_agnostic_le` would encode little endian and read on either little or big endian. `endian_agnostic_be` would do the same but encode as big endian.

There's probably already a crate out there that does this, so it could be as easy as integrating support for that. The real difficulty is probably going to be testing the functionality.

**Comment by syrusakbary** [comment]
Tests might be possible via a combination of:
* Have an example Rust program that compiles to a mips executable (bug endian)
* Run that program with qemu and verify the output

**Comment by djkoloski** [comment]
Fixed by 06dc58240f21f35fe7d1db75b2c88ea69365d63d. I put a few endian-specific tests in the validation section, those seem to be doing a good job of ensuring the endianness is correct.
