### ISSUE TITLE
Fast serialization?

### ISSUE THREAD

**Issue by kvark** [djkoloski/rkyv#108]
> Zero-copy deserialization framework for Rust 

Is it in scope of the library to provide fast serialization?

Looking through the serializers in the docs, it's not clear to me when to use `BufferSerializer` versus `AlignedSerializer`. Maybe a bit of documentation in the `ser` module itself could help guide this?

Also, I don't want the memory to be growing (since it involves copies and generates worse code). I'd want something like an arena backing for the serialzier, so that it ends up producing a list of (exponentially sized) chunks. Is this something on your radar, or would require me to implement my own serializer?

Side note: the library seems to have a fat layer of generics on it, making it impenetrable for the eyes. For example, looking at [deserialize](https://docs.rs/rkyv/0.5.1/rkyv/trait.Deserialize.html#tymethod.deserialize) I have no idea what is the exact type returned, and how is this going to be zero-copy.

**Comment by djkoloski** [comment]
Yes, fast serialization is definitely a goal of this library. In general, it is actually [pretty fast already](https://github.com/djkoloski/rust_serialization_benchmark) and you can get some additional speed on `ArchiveCopy` types if you can enable the `specialization` feature.

`BufferSerializer` is meant primarily for `no_std` environments where you want to serialize into fixed-size byte arrays. The idea is that `WriteSerializer` is the generic, less-performant version of `AlignedSerializer`. Eventually, there will be an equivalent `AlignedBufferSerializer` that's the more-performant version of `BufferSerializer`. I think documenting the `ser` module more would help clarify that.

Using an arena backing will work out of the box. You would just need to implement `Write` for it and wrap it in a `WriteSerializer`. With some extra legwork you could probably write a more performant version that supports emplacement like `AlignedSerializer` does, but you'd need to be able to guarantee enough space to fit whatever type is being emplaced. This is the sort of thing that more crates would help, so we'll get there eventually!

I'll document the type parameters more for the next release. In this specific case, `Deserialize<T, D>` is a trait saying "this type can be deserialized to a `T` using a `D` deserializer". It has to be implemented this way to avoid recursive type bounds and provide flexibility for the same type to deserialize to many different types (e.g. `u32` may deserialize to `u32` or `usize` depending on your features).

**Comment by djkoloski** [comment]
Some ideas for the upcoming perf pass:

- Serialization implementations that need to perform allocations (e.g. store resolvers in a vec) may benefit from reusing memory. Swapping `Vec`s out for a serializer-provided scratch space could give some reasonable perf improvements and allow implementations that are currently `alloc`-only to function on total `no_std`.
- A small string optimization could reduce the size of many benchmarks that have small strings in many places.

**Comment by djkoloski** [comment]
Validation performance has been improved significantly by cd35eb6abd239fb9be22590da4c4015a56bbcf3c through e6ae0f7c7d480fa06de2f9120dc6db65b0e79f54. Benchmarks:

```
bench | old       | new       | change
------|-----------|-----------|---------
log   | 1.2067 ms | 864.55 us | -28.354%
mesh  | 98.728 ns | 11.593 ns | -88.258%
mc_sd | 1.2781 ms | 742.21 us | -41.929%
```

This looks especially good because the time it takes to validate is correlating more strongly with the amount of validation work that actually has to be done.

**Comment by djkoloski** [comment]
Serialization performance has been improved significantly by 57455beb0e704a6e2cb857a4ec1725f0999cbe3e through 02261ef4b8e46bddb88b495e53473904fcd7e7a3. I don't have proper benchmarks to give definitive results, but here are the numbers from benching in a noisy environment:

```
stable:

bench | serialize
------|----------
log   | 412.96 us
mesh  | 1.2192 ms
mc_sd | 623.50 us

nightly with copy feature:

bench | serialize
------|----------
log   | 391.85 us
mesh  | 342.18 us
mc_sd | 622.76 us
```

Given the noisy environment, these numbers look pretty good and should get even better during a proper benchmark.

**Comment by djkoloski** [comment]
Short string optimization added in 87cef3a3033ea35dec9743217667afd23bac2ce4. No measurable effect on serialization performance, but the size benchmarks have decreased:

```
bench |  before  |  after 
------|----------|---------
log   |  1065784 | 1011488
mesh  |  6000008 | 6000008
mc_sd |   725208 |  596952
```

I think that's the end of the optimizations for 0.7. Closing this issue.
