### ISSUE TITLE
Support tinyvec

### ISSUE THREAD

**Issue by Kixiron** [djkoloski/rkyv#110]
Supporting [`tinyvec::TinyVec`](https://docs.rs/tinyvec/1.2.0/tinyvec/enum.TinyVec.html), [`tinyvec::ArrayVec`](https://docs.rs/tinyvec/1.2.0/tinyvec/struct.ArrayVec.html) and [`tinyvec::SliceVec`](https://docs.rs/tinyvec/1.2.0/tinyvec/struct.SliceVec.html) under feature flags would be sweet

**Comment by djkoloski** [comment]
Fixed by ba7f5b3842b7e19987674222ca7116839caf0727
