### ISSUE TITLE
Rkyv 0.6 can't deserialized previously-serialized artifact

### ISSUE THREAD

**Issue by syrusakbary** [djkoloski/rkyv#116]
We just upgraded rkyv from `0.4.3` to `0.6.0`.

I've been spending a bit of time debugging this: https://github.com/wasmerio/wasmer/pull/2250

And I realize that the issue is on rkyv, as it work well when downgrading from `0.4.3` to `0.6.0` (here's [the downgrade commit](https://github.com/wasmerio/wasmer/pull/2250/commits/4c54d863ce0a3edd319a962ac69bdd8877867753))

In a nutshell, this fails (serializing to then deserialize in the same program and process).
https://github.com/wasmerio/wasmer/blob/376703cad2f72ea7bc70801df028e0b4043a7914/lib/engine-jit/src/artifact.rs#L350-L368

```rust
        let serialized_data = self.serializable.serialize()?;
        let deserialized = unsafe { SerializableModule::deserialize(&serialized_data) };
```

Then, I downgraded to 0.4.3 and it started working properly again.

**Comment by djkoloski** [comment]
This was a problem with deserializing empty vectors and vectors of ZSTs. The issue has been fixed as of 1f3fec0b9789ec0b9dfa4d2b8747167d83f23260 and updating to 0.6.1 will fix wasmer.
