### ISSUE TITLE
Attach endianness to serialized data. Check when deserializing

### ISSUE THREAD

**Issue by syrusakbary** [djkoloski/rkyv#117]
Rkyv is endianness dependent. Right now, we are doing manual work to:
1. Append an endian flag to the serialized data: https://github.com/wasmerio/wasmer/blob/master/lib/engine-native/src/serialize.rs#L66-L70
2. Check the flag when deserializing the data (it takes just the last byte): https://github.com/wasmerio/wasmer/blob/master/lib/engine-native/src/serialize.rs#L84-L88

It would be great if rkyv could do that for us automatically :)

**Comment by djkoloski** [comment]
Would endian-agnostic archives solve this? Those are currently slated for 0.7 through `rend`.

**Comment by syrusakbary** [comment]
> Would endian-agnostic archives solve this?

Completely! That would be an even better solution!

**Comment by djkoloski** [comment]
Closing in favor of #104.
