### ISSUE TITLE
Provide `#[archive(as = "...")]` for users to provide their own archive types

### ISSUE THREAD

**Issue by djkoloski** [djkoloski/rkyv#128]
With the changes around `ArchiveCopy` (#119) the idea of a type being archiveable as itself needs to be changed too.

Adding `#[archive(self)]` to a type should:
- Add `T: Archive<Archived = Self>` bounds for each of the fields
- Error on any uses of `#[archive_attr]` or other attributes except `#[archive(copy_safe)]`
- Ensure that enums have an appropriate `repr`
- Not generate an archived version of the type

**Comment by djkoloski** [comment]
Also provide the syntax `#[archive(self = "...")]` for these kinds of cases:

```rust
#[archive(self = "Self<T::Archived>")]
struct Example<T>(T);
```

Which currently generate an `ArchivedExample<T>` when they could just archive to `Example<Archived<T>>`. This conflicts with the bound `T: Archive<Archived = Self>` but I think it will be okay once `project_struct` gets switched to `ptr::addr_of_mut` because it will still cause a compiler error.

**Comment by djkoloski** [comment]
Fixed by 818e9f0f1d94c1159b940eacc5c2b6b6fe14bdb4

**Comment by dvc94ch** [comment]
Fantastic, I was just looking for how to do this!

**Comment by dvc94ch** [comment]
I wonder if there is a way to implement `AsRef<[u8]>` for types that are `#[archive(as = "Self")]`?

**Comment by djkoloski** [comment]
You can implement `AsRef` the same as you normally would, this parameter just swaps out the generated archived struct for the one you specify. So if you implement `AsRef<[u8]>` for a struct, it will archive as itself with `#[archive(as = "Self")]`.

**Comment by dvc94ch** [comment]
Yes, using the zerocopy crate to derive AsBytes for simple structs.
