### ISSUE TITLE
`no_std` build fails in 0.7.0 branch

### ISSUE THREAD

**Issue by PiDelport** [djkoloski/rkyv#148]
The 0.7.0 branch currently fails to build with `std` disabled:

```
$ cargo build -p rkyv --no-default-features
…
error[E0432]: unresolved import `std`
  --> rkyv/src/core_impl/primitive.rs:19:5
   |
19 | use std::usize;
   |     ^^^ use of undeclared crate or module `std`

```

As far as I can tell, the breaking change is this line of 6d8adb1:

https://github.com/djkoloski/rkyv/commit/6d8adb180adaa1bf80028f9029d85e887f099b9b#diff-ff3ca14deb34cdee57667b1f03d1115bc663b0b7569edf18d061881ed9e5b7d6R19

**Comment by djkoloski** [comment]
Thanks for the help, should be fixed by 19cb7f3585c45699bcb858cbfa1fa54760b4bb85, can you give that a try?
