### ISSUE TITLE
Support indexmap

### ISSUE THREAD

**Issue by MikaelCall** [djkoloski/rkyv#150]
indexmap is a popular crate for controlling order in hashmaps. It'd be very nice if the required traits could be implemented for `indexmap::IndexMap` or if there is a simple workaround using the [#with(..)] attribute on fields?

**Comment by djkoloski** [comment]
I'll take a look. If I remember correctly, there's already rkyv support for indexmap floating around. I forget where it is though.

**Comment by djkoloski** [comment]
Looks there was some work done for wasmer/cranelift [a while ago](https://github.com/ailisp/rkyv/commit/d577292bd9bbf27dd6fa490a987d45f3080df9b2), but I don't know where it ended up. If I'm understanding `IndexMap` correctly, it's a vector with all the elements hashed so you can look up an index quickly. That shouldn't be too hard to implement, and should be able to be done in terms of already-existing functionality. I'll see if I can provide an implementation for the next release.

**Comment by djkoloski** [comment]
Initial implementation done in bf3b63ff1fb52f180f070cdc67cfae270a6f39e5. Still needs:

- More traits implemented
- Impls for `IndexSet`

**Comment by djkoloski** [comment]
Fixed by d1d06930b5ca79e5a9f4d7346ec6fa02f45f1b1b.
