### ISSUE TITLE
Derive Hash for archived value when struct has Vec fails

### ISSUE THREAD

**Issue by MikaelCall** [djkoloski/rkyv#151]
This is a MNVE that I expected to work

```rust
use rkyv::{Archive, Deserialize, Serialize};

#[derive(Archive, Deserialize, Serialize, PartialEq, Eq, Hash)]
#[archive(derive(PartialEq, Eq, Hash))]
struct Test {
    v: Vec<i32>,
}
```

**Comment by djkoloski** [comment]
Fixed by dbd2de1e518d80610476fa63e3e41da25e8475cf, this fix will be in the next bugfix release (0.6.7). I also did a pass on all std containers, those will be in the next minor version (0.7).
