### ISSUE TITLE
Support atomic variants of `usize` and `isize`

### ISSUE THREAD

**Issue by JoeyBF** [djkoloski/rkyv#160]
These are the only numeric atomics that are missing from `core_impl` as far as I can tell. I see there's support for both `AtomicU64` and `usize`, but maybe there's some subtle issue that makes it hard to combine the two?

**Comment by djkoloski** [comment]
`usize` didn't have an `Archive` implementation for a long time, but that changed somewhat recently. Atomics have been supported for a while, so I think this is just an oversight.

**Comment by djkoloski** [comment]
Fixed by aa38292bc7ebafd406bf5826b3588deff80e00d3
