### ISSUE TITLE
Include license file in rkyv crate and others

### ISSUE THREAD

**Issue by remilauzier** [djkoloski/rkyv#162]
Hi, fedora would prefer to have access to the license file directly in the crate on crate.io instead of having to downloading it separately.

**Comment by djkoloski** [comment]
This would just require copying the `LICENSE` into the crate directory, right? That should be an easy fix.

**Comment by djkoloski** [comment]
Fixed by f8480b4b9b7f4edb44bf9896c3b0454ec6b80cd4
