### ISSUE TITLE
document/specify the format

### ISSUE THREAD

**Issue by dvc94ch** [djkoloski/rkyv#25]
One advantage of using specified codecs is interoperability. I think it would be beneficial to have a specification.

**Comment by djkoloski** [comment]
Just to clarify, rkyv works by generating new types that use relative pointers and have cross-platform compatibility. As opposed to a more traditional serialization format, these types are stored directly in a usable format to enable zero-copy deserialization. Would documentation on how those types are generated and laid out suitably fill this gap? rkyv does not have a codec in a traditional sense.

**Comment by dvc94ch** [comment]
Yes, that is what I'm after.

**Comment by djkoloski** [comment]
Fixed by 82adbdaf2bbe7bad37cbc0bc26fed6dfda2ee9e7. Book is available at [djkoloski.github.io/rkyv](https://djkoloski.github.io/rkyv) with a section on how types are generated and laid out.
