### ISSUE TITLE
Ready for embedded?

### ISSUE THREAD

**Issue by xieren58** [djkoloski/rkyv#70]
Is it ready for embedded software(no_std)?

**Comment by djkoloski** [comment]
rkyv supports no_std, but there's currently an issue with it (#69) that will be resolved as soon as possible.

**Comment by xieren58** [comment]
This is really cool, thank you for your hardwork.

**Comment by djkoloski** [comment]
`no_std` support is fixed by a2fcaa60ae7cffa191c02a826b51133f6128ae87 and released in 0.4.1.
