### ISSUE TITLE
User methods on storage types?

### ISSUE THREAD

**Issue by 0x7CFE** [djkoloski/rkyv#71]
Hello, I'm trying to wrap my head around `rkyv` architecture. So far it looks awesome, but I don't quite understand, whether it is possible to create a system where one can call methods on a deserialized struct as if it was the original one?

If I'm not mistaken, deserialized struct is structurally equivalent, but uses mirror `Archive` types, so it's not possible. However, maybe there's a way to abstract over it?

**Comment by djkoloski** [comment]
Great question, thanks for asking. There are two approaches you could take here:

1. Use a macro to duplicate some impls for both the regular and archived versions
2. Define a trait and implement it on both types

You could technically also use #[archive(copy)] to use the same type in both places, but this isn’t possible most of the time. I think that both main approaches have pros and cons but overall I think a trait based approach would make it easiest to abstract over the underlying types in your own code. That convenience may not be worth the price of making so many traits though!

**Comment by djkoloski** [comment]
Closing for now, feel free to reopen if you have further questions. :)
