### ISSUE TITLE
Origin of name?

### ISSUE THREAD

**Issue by khionu** [djkoloski/rkyv#72]
As on the tin. Might be good to add to the FAQ

**Comment by djkoloski** [comment]
It's hiding in plain sight:

> rkyv (*archive*) is a zero-copy deserialization framework for Rust.

The [`archive` crate](https://crates.io/crates/archive) was and is still name-squatted by someone who didn't respond to my emails. I ended up changing the name of the project in d6a0ccba0d6befc230c4555225c9fcd18d8d4a64 to something that looks *cool* but could be pronounced the same.

**Comment by khionu** [comment]
Ahhhh, so that's what you meant, clever!
