### ISSUE TITLE
comparison to https://github.com/near/borsh?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [djkoloski/rkyv#74]
is rkyv consistent cashing?

**Comment by djkoloski** [comment]
Borsh is a more traditional serialization library, with a serialized format that must be deserialized before any data can be accessed. It looks like it's also oriented around secure applications, whereas rkyv is intended as a general-purpose zero-copy deserialization library.

The primary draw of zero-copy deserialization is that no deserialization work is required to access and update data. This will give a decent performance boost in most cases, and some applications that deserialize a lot of data (like games and media) can get a very sizeable performance boost.

I encourage you to take a look at the [serialization benchmarks](https://github.com/djkoloski/rust_serialization_benchmark) for an idea of how the two libraries compare for some basic operations on different data sets.
