### ISSUE TITLE
arbitrary size integers?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [djkoloski/rkyv#75]
like u4 or u10?

**Comment by djkoloski** [comment]
rkyv doesn't offer any extensions to rust primitives out of the box, but if a library added arbitrary size integers then they could also add rkyv support for them. Typically this is done with a feature flag, a lot of crates do this for serde support.

One of the primary features of rkyv is its open type system. Unlike other zero-copy deserialization libraries, it doesn't rely on external schemas. This lets users add their own archivable types. Even types like `bigint`s that have an array backing can be supported by rkyv.
