### ISSUE TITLE
Add feature comparison

### ISSUE THREAD

**Issue by pickfire** [djkoloski/rkyv#76]
It would be good to let users know what is supported and what is not, when comparing to other contenders like capn' proto and flatbuffers.

https://github.com/djkoloski/rkyv/issues/67#issuecomment-799548975

The comment there is already good, maybe we can compare some technical details aside from features. At least one thing not mentioned there is the ergonomics in rust, as it is built in rust having a derive will be better than writing schemas, but still having schemas is able to make it cross-language easier.

Heh, maybe rust is the schema where code from other languages can be generated for something like FFI through the derive?

**Comment by djkoloski** [comment]
Fixed by d3ecb61acc41f9e0d55b6560450506e142463bdf. A feature comparison matrix is available [in the book](davidkoloski.me/rkyv/feature-comparison.html) and any pull requests to improve the quality are welcome!
