### ISSUE TITLE
Provide implementations for Uuid

### ISSUE THREAD

**Issue by djkoloski** [djkoloski/rkyv#88]
There are a couple popular crates that could use some outreach to add rkyv support. Uuid is a good one to start with and it will give a feel for what the process will be like.

**Comment by pickfire** [comment]
I am trying to add pyo3 support for chrono in https://github.com/chronotope/chrono/pull/542 which maybe I could as well add one for rkyv as well.

**Comment by djkoloski** [comment]
That would be awesome! Feel free to add me as a reviewer if you want a second pair of eyes. We can also open a new tracking issue for `chrono`.

**Comment by pickfire** [comment]
Just wondering, if rkyv serialized and saved it into a file. Then a library changes its internal representation, wouldn't that breaks the de-serialization of the data?

**Comment by djkoloski** [comment]
Yes, that would break deserialization. That’s a case where we’d need to have schema migration support.

**Comment by pickfire** [comment]
If we have schema migration support wouldn't that slows stuff down?

**Comment by djkoloski** [comment]
There are a few options for schemas:

1. rkyv types that support schema evolution similarly to FlatBuffers and Cap'n Proto (this is what [protoss](https://github.com/djkoloski/crate_ideas#protoss) is aimed to be)
2. Schema migration for static data via external schemas (this is what [skema](https://github.com/djkoloski/crate_ideas#skema) is aimed to be)

I'm sure there are more options too, but I don't think we need to sacrifice ZCD to get schema evolution.

**Comment by djkoloski** [comment]
Fixed by 580c17622046c5e9193a523b95b305355be98676
